import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Navbar } from "../components";
import { Header, About, Work, Skills, Footer } from "../container";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Anas Abbasi - Website Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Navbar />
        <Header />
        <About />
        <Work />
        <Skills />
        <Footer />
      </div>
    </div>
  );
}
