import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Navbar } from "../components";

export default function Home({ allPosts }) {
  // console.log(allPosts);
  return (
    <div className="">
      <Head>
        <title>Anas Abbasi - Website Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Navbar />
      </div>
    </div>
  );
}
